### ISSUE TITLE
[Bug]: Errors when running native:serve & native:build

### ISSUE THREAD

**Issue by ConrDev** [NativePHP/electron#13] opened 2023-07-20 23:45 UTC
### What happened?

After following the docs and installing NativePHP on a laravel 10.x sail project with inertia.js, i ran `native:install` and ran `native:serve` but came across the following error.

## `native:serve`:
![native:serve](https://github.com/NativePHP/electron/assets/20028486/04c11fdb-d287-472e-aed0-868749ecfbf1)

Next i tried building the app but also gave me an error.

## `native:build`:
![native:build](https://github.com/NativePHP/electron/assets/20028486/ba6e2d6d-e01b-4b30-9b57-8dfd3d0a562d)

### How to reproduce the bug

i installed NativePHP like documented and ran `native:serve`

### Package Version

0.1.0

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

macOS

**Comment by bpjuli22** [comment] 2023-07-21 04:36
I also got same error from my linux based os i.e pop os

**Comment by bpjuli22** [comment] 2023-07-21 04:48
inside ../../resources/php" from "src/main/index.js,
the resource is missing the php folder and cacert.pem
May be the initial builder didn't create those files or folders

**Comment by IllesAprod** [comment] 2023-07-21 06:12
I experience same issue!

**Comment by ConrDev** [comment] 2023-07-21 07:37
> inside ../../resources/php" from "src/main/index.js,
> 
> the resource is missing the php folder and cacert.pem
> 
> May be the initial builder didn't create those files or folders
> 
> 

ye i think there are some issues with the released files(package), thus the reason of those missing files etc.

**Comment by jonsugar** [comment] 2023-07-21 08:12
Duplicate of #10 

You can work around if is you are willing to hack! See, https://github.com/NativePHP/electron/issues/10#issuecomment-1644651637

**Comment by axyr** [comment] 2023-07-21 12:55
This sound more like an npm problem..

I had this issue last friday and then there were outages..

**Comment by mpociot** [comment] 2023-07-25 15:38
Fixed in 0.1.1

**Closed by mpociot** 2023-07-25 15:38 UTC
Labels: bug
